- docs/resources/gcore_storage_s3.md
- gcore/resource_gcore_storage_s3.go
> add msk location to s3 storage

- gcore/provider.go
> add default api urls

- docs/resources/gcore_cdn_origingroup.md
- docs/resources/gcore_cdn_resource.md
- docs/resources/gcore_cdn_rule.md
- docs/resources/gcore_cdn_sslcert.md
- examples/resources/gcore_cdn_origingroup/resource.tf
- examples/resources/gcore_cdn_resource/resource.tf
- examples/resources/gcore_cdn_rule/resource.tf
- examples/resources/gcore_cdn_sslcert/resource.tf
- gcore/provider.go
Updated urls for cdn app and added default url.
> Updated all cdn urls

- go.mod
- go.sum
> fix cdn deprecated urls

- docs/resources/gcore_cdn_origingroup.md
- docs/resources/gcore_cdn_resource.md
- docs/resources/gcore_cdn_rule.md
- docs/resources/gcore_cdn_sslcert.md
- examples/resources/gcore_cdn_origingroup/resource.tf
- examples/resources/gcore_cdn_resource/resource.tf
- examples/resources/gcore_cdn_rule/resource.tf
- examples/resources/gcore_cdn_sslcert/resource.tf
- gcore/provider.go
> Remove old examples

- go.mod
- go.sum
> updated lib

- docs/resources/gcore_instance.md
- examples/resources/gcore_instance/resource.tf
- gcore/resource_gcore_instance.go
- gcore/utils.go
resource_gcore_instance.metadata deprecated
> resource_gcore_instance.metadata_map added

- gcore/resource_gcore_lblistener.go
- gcore/resource_gcore_loadbalancer.go
- go.mod
- go.sum
limited to 1, updated method fixed
secret_id, sni_secret_id added to listeners
> resource_gcore_loadbalancer.listener updated

- gcore/resource_gcore_dns_zone_record.go
set dns zone record enabled param to true by default
> set dns zone record enabled param to true by default

- gcore/provider.go
- gcore/resource_gcore_dns_zone_record.go
> fix dns rrset meta setter

- docs/resources/gcore_dns_zone.md
- docs/resources/gcore_dns_zone_record.md
- examples/resources/gcore_dns_zone/import.sh
- examples/resources/gcore_dns_zone_record/import.sh
- gcore/resource_gcore_dns_zone_record.go
> add docs for dns zone & record import

- gcore/resource_gcore_cdn_rule.go
- go.mod
- go.sum
Pass options for creating rule request as previously rule created without options
> add options for rule creation request

- examples/resources/gcore_cdn_origingroup/resource.tf
- examples/resources/gcore_cdn_resource/resource.tf
- examples/resources/gcore_cdn_rule/resource.tf
- examples/resources/gcore_cdn_sslcert/resource.tf
- gcore/resource_gcore_cdn_origin_group.go
- gcore/resource_gcore_cdn_resource.go
- gcore/resource_gcore_cdn_rule.go
- gcore/resource_gcore_cdn_sslcerts.go
* add terraform import support for CDN resources
* update CDN resources examples
> CDN resources: add terraform import support, update examples

- docs/index.md
- docs/resources/gcore_cdn_origingroup.md
- docs/resources/gcore_cdn_resource.md
- docs/resources/gcore_cdn_rule.md
- docs/resources/gcore_cdn_sslcert.md
- examples/provider/provider.tf
- gcore/provider.go
- go.mod
- go.sum
update docs from terraform resources
> update CDN resources docs

- .github/workflows/release.yml
- .goreleaser.yml
- gcore/resource_gcore_cdn_resource.go
- go.mod
- go.sum
* update terraform release.yml
* update terraform goreleaser
* fix origin proto on res creation
* update default values for 'custom_values' option & 'secondary_hostnames'
> cdn improments

- docs/data-sources/gcore_router.md
- docs/resources/gcore_router.md
- gcore/data_source_gcore_router.go
- gcore/resource_gcore_router.go
Actualized interfaces field in router resouce and data source
> Interfaces in router resource and data source

- .gitlab-ci.yml
> gitlab ci tests added

- gcore/data_source_gcore_network.go
- gcore/data_source_gcore_network_test.go
- gcore/data_source_gcore_securitygroup_test.go
- gcore/data_source_gcore_subnet.go
- gcore/data_source_gcore_subnet_test.go
- gcore/resource_gcore_network.go
- gcore/resource_gcore_network_test.go
- gcore/resource_gcore_subnet.go
- gcore/resource_gcore_subnet_test.go
- gcore/utils_test_metadata.go
- go.mod
- go.sum
Added metadata support for nets and subnets
> net_subnet_metadata support

- docs/resources/gcore_cdn_rule.md
- examples/resources/gcore_cdn_rule/resource.tf
- gcore/resource_gcore_cdn_rule_test.go
> add rule weight param to docs and examples

- docs/resources/gcore_dns_zone.md
- docs/resources/gcore_dns_zone_record.md
- gcore/resource_gcore_dns_zone.go
- gcore/resource_gcore_dns_zone_record.go
> Add customizable create and delete timeouts for DNS zone and DNS zone record resources

- gcore/resource_gcore_instance.go
* Fixed bug in updating interface with type 'reserved_fixed_ip'
> GCLOUD2-9399: Bug in updating interface with type 'reserved_fixed_ip'
